# Generated by Django 5.0.3 on 2024-03-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluída')], default='pendente', max_length=9)),
                ('categoria', models.CharField(choices=[('verificar', 'Verificar'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='verificar', max_length=10)),
            ],
        ),
    ]
