# Generated by Django 5.0.3 on 2024-04-02 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='alterado_por',
            field=models.CharField(default='nome_de_usuario_padrao', max_length=100),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='criado_por',
            field=models.CharField(default='nome_de_usuario_padrao', max_length=100),
        ),
    ]
